/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rekam.medis;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.*;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
/**
 *
 * @author HP
 */
public class FormRekamMedis extends javax.swing.JFrame {
    String user = "root";
    String password = "";
    String url = "jdbc:mysql://localhost/rekam_medis";
    /**
     * Creates new form FormRekamMedis
     */
    String[] columnNames = {"ID Dokter", "Nama Dokter", "Spesialis", "Jenis Kelamin", "No Telp", "Alamat", "Email"};
    private DefaultTableModel model;
    private JTable table;
    public FormRekamMedis() {
        initComponents();
        
    }

    void isiDokter(){
        try{
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM dokter";
            ResultSet rs = st.executeQuery(sql);
            idDokter.removeAllItems();
            while(rs.next()){
                idDokter.addItem(rs.getString("idDokter"));
            }
        }catch(SQLException e){
          System.out.println("Koneksi gagal"+e.toString());
        }
    }
    
    void aktif(){
        tglMasuk.setEnabled(true);
        tglKeluar.setEnabled(true);
        diagnosaField.setEnabled(true);
        ruanganKamar.setEnabled(true);
        namaPasien.setEnabled(true);
        jkLakiPasien.setEnabled(true);
        jkPerempuanPasien.setEnabled(true);
        tglLahir.setEnabled(true);
        noHPPasien.setEnabled(true);
        alamatPasien.setEnabled(true);
        namaPenanggung.setEnabled(true);
        jkLakiPenanggung.setEnabled(true);
        jkPerempuanPenanggung.setEnabled(true);
        noHPPenanggung.setEnabled(true);
        alamatPenanggung.setEnabled(true);
    }
    void nonaktif(){
        noDataPasien.setEnabled(false);
        tglMasuk.setEnabled(false);
        tglKeluar.setEnabled(false);
        diagnosaField.setEnabled(false);
        ruanganKamar.setEnabled(false);
        idDokter.setEnabled(false);
        namaDokter.setEnabled(false);
        namaPasien.setEnabled(false);
        jkLakiPasien.setEnabled(false);
        jkPerempuanPasien.setEnabled(false);
        tglLahir.setEnabled(false);
        noHPPasien.setEnabled(false);
        alamatPasien.setEnabled(false);
        namaPenanggung.setEnabled(false);
        jkLakiPenanggung.setEnabled(false);
        jkPerempuanPenanggung.setEnabled(false);
        noHPPenanggung.setEnabled(false);
        alamatPenanggung.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private Object[][]getData(){
        Object[][]data = null;
        try{
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT rekammedis.idRekamMedis,rekammedis.noDataPasien,rekammedis.idDokter,rekammedis.diagnosa,rekammedis.tglKeluar,datapasien.tglMasuk,datapasien.ruanganKamar,datapasien.namaPasien,datapasien.jkPasien,datapasien.TglLahirPasien,datapasien.noHPPasien,datapasien.alamatPasien,datapasien.namaPenanggung,datapasien.noHPPenanggung,datapasien.jkPenanggung,datapasien.alamatPenanggung FROM rekammedis JOIN datapasien ON rekammedis.noDataPasien = datapasien.noDataPasien";
            ResultSet rs = st.executeQuery(sql);
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            data = new Object[rowCount][14];
            int no = -1;
            while(rs.next()){
                no = no+1;
                data[no][0] = rs.getString("noDataPasien");
                data[no][1] = rs.getString("tglMasuk");
                data[no][2] = rs.getString("tglKeluar");
                data[no][3] = rs.getString("ruanganKamar");
                data[no][4] = rs.getString("diagnosa");
                data[no][5] = rs.getString("namaPasien");
                data[no][6] = rs.getString("jkPasien");
                data[no][7] = rs.getString("TglLahirPasien");
                data[no][8] = rs.getString("noHPPasien");
                data[no][9] = rs.getString("alamatPasien");
                data[no][10] = rs.getString("namaPenanggung");
                data[no][11] = rs.getString("noHPPenanggung");
                data[no][12] = rs.getString("jkPenanggung");
                data[no][13] = rs.getString("alamatPenanggung");
            }
        }catch(SQLException e){
            System.out.println("Koneksi gagal"+e.toString());
        }
        return data;
    }
    
    private Object[][]getDataSearch(){
        Object[][]data = null;
        try{
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT rekammedis.idRekamMedis,rekammedis.noDataPasien,rekammedis.idDokter,rekammedis.diagnosa,rekammedis.tglKeluar,datapasien.tglMasuk,datapasien.ruanganKamar,datapasien.namaPasien,datapasien.jkPasien,datapasien.TglLahirPasien,datapasien.noHPPasien,datapasien.alamatPasien,datapasien.namaPenanggung,datapasien.noHPPenanggung,datapasien.jkPenanggung,datapasien.alamatPenanggung FROM rekammedis JOIN datapasien ON rekammedis.noDataPasien = datapasien.noDataPasien WHERE rekammedis.noDataPasien LIKE '%"+cariField.getText()+"%' OR datapasien.namaPasien LIKE '%"+cariField.getText()+"%'";
            ResultSet rs = st.executeQuery(sql);
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            data = new Object[rowCount][14];
            int no = -1;
            while(rs.next()){
                no = no+1;
                data[no][0] = rs.getString("noDataPasien");
                data[no][1] = rs.getString("tglMasuk");
                data[no][2] = rs.getString("tglKeluar");
                data[no][3] = rs.getString("ruanganKamar");
                data[no][4] = rs.getString("diagnosa");
                data[no][5] = rs.getString("namaPasien");
                data[no][6] = rs.getString("jkPasien");
                data[no][7] = rs.getString("TglLahirPasien");
                data[no][8] = rs.getString("noHPPasien");
                data[no][9] = rs.getString("alamatPasien");
                data[no][10] = rs.getString("namaPenanggung");
                data[no][11] = rs.getString("noHPPenanggung");
                data[no][12] = rs.getString("jkPenanggung");
                data[no][13] = rs.getString("alamatPenanggung");
            }
        }catch(SQLException e){
            System.out.println("Koneksi gagal"+e.toString());
        }
        return data;
    }
    
    void tampilGrid(Object[][]tampil){
        String[] columnNames = {"NO Data Pasien", "TGL Masuk", "TGL Keluar", "Ruangan Kamar", "Diagnosa", "Nama Pasien", "JK Pasien", "TGL Lahir Pasien", "NO HP Pasien", "Alamat Pasien", "Nama Penanggung", "NO HP Penanggung", "JK Penanggung", "Alamat Penanggung"};
        model = new DefaultTableModel(tampil, columnNames);
        table = new JTable(model);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        for (int i = 0; i < table.getColumnCount(); i++) {
          DefaultTableColumnModel colModel = (DefaultTableColumnModel) table.getColumnModel();
          TableColumn col = colModel.getColumn(i);
          int width = 0;
          TableCellRenderer renderer = col.getHeaderRenderer();
          for (int r = 0; r < table.getRowCount(); r++) {
            renderer = table.getCellRenderer(r, i);
            Component comp = renderer.getTableCellRendererComponent(table, table.getValueAt(r, i),false, false, r, i);
            width = Math.max(width, comp.getPreferredSize().width);
          }
          col.setPreferredWidth(width + 50);
        }
        
        jScrollPane2.setViewportView(table);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pasienGroup = new javax.swing.ButtonGroup();
        penanggungGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        cariField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cariBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        noHPPasien = new javax.swing.JTextField();
        blabka2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namaPasien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jkLakiPasien = new javax.swing.JRadioButton();
        jkPerempuanPasien = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatPasien = new javax.swing.JTextArea();
        blabka = new javax.swing.JLabel();
        tglLahir = new com.toedter.calendar.JDateChooser();
        blabka1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tglMasuk = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        tglKeluar = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosaField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noDataPasien = new javax.swing.JTextField();
        ruanganKamar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        idDokter = new javax.swing.JComboBox<>();
        namaDokter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        noHPPenanggung = new javax.swing.JTextField();
        blabka3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        namaPenanggung = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jkLakiPenanggung = new javax.swing.JRadioButton();
        jkPerempuanPenanggung = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        alamatPenanggung = new javax.swing.JTextArea();
        blabka5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(485, 440));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Cari");

        cariField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cariField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariFieldKeyPressed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        saveBtn.setText("Save");

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        exitBtn.setText("Exit");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rekam/medis/rekam medis.png"))); // NOI18N
        jLabel1.setText("  Rekam Medis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        cariBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rekam/medis/search.png"))); // NOI18N
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        blabka2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabka2.setText("Alamat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Data Pasien");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Nama");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Jenis Kelamin");

        pasienGroup.add(jkLakiPasien);
        jkLakiPasien.setText("Laki-laki");

        pasienGroup.add(jkPerempuanPasien);
        jkPerempuanPasien.setText("Perempuan");

        alamatPasien.setColumns(20);
        alamatPasien.setRows(5);
        jScrollPane3.setViewportView(alamatPasien);

        blabka.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabka.setText("TGL Lahir");

        blabka1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabka1.setText("NO HP ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blabka)
                            .addComponent(jLabel10)
                            .addComponent(blabka1)
                            .addComponent(blabka2)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jkLakiPasien)
                                .addGap(18, 18, 18)
                                .addComponent(jkPerempuanPasien))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(noHPPasien, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tglLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jkLakiPasien)
                    .addComponent(jkPerempuanPasien))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(blabka)
                    .addComponent(tglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(blabka1)
                    .addComponent(noHPPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blabka2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("TGL Masuk");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("TGL Keluar");

        diagnosaField.setColumns(20);
        diagnosaField.setRows(5);
        jScrollPane1.setViewportView(diagnosaField);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("No Data Pasien");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Ruangan Kamar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Diagnosa");

        noDataPasien.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        ruanganKamar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("ID Dokter");

        idDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDokterActionPerformed(evt);
            }
        });

        namaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaDokterActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setText("Nama Dokter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noDataPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tglMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(namaDokter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(ruanganKamar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(noDataPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(tglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(tglKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ruanganKamar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(idDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blabka3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabka3.setText("Alamat");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Data Penanggung Jawab");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("Nama");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        penanggungGroup.add(jkLakiPenanggung);
        jkLakiPenanggung.setText("Laki-laki");

        penanggungGroup.add(jkPerempuanPenanggung);
        jkPerempuanPenanggung.setText("Perempuan");

        alamatPenanggung.setColumns(20);
        alamatPenanggung.setRows(5);
        jScrollPane4.setViewportView(alamatPenanggung);

        blabka5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabka5.setText("NO HP ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(blabka5)
                            .addComponent(blabka3)
                            .addComponent(jLabel14))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPenanggung, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jkLakiPenanggung)
                                .addGap(18, 18, 18)
                                .addComponent(jkPerempuanPenanggung))
                            .addComponent(noHPPenanggung, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPenanggung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jkLakiPenanggung)
                    .addComponent(jkPerempuanPenanggung))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(blabka5)
                        .addGap(15, 15, 15)
                        .addComponent(blabka3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(noHPPenanggung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(51, 51, 51)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cariBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(saveBtn)
                            .addComponent(cancelBtn)
                            .addComponent(exitBtn))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        nonaktif();
        isiDokter();
        tampilGrid(getData());
    }//GEN-LAST:event_formWindowActivated

    private void cariFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            tampilGrid(getDataSearch());
        }
    }//GEN-LAST:event_cariFieldKeyPressed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
         if(table.getSelectedRow() != -1) {
            try{
                Connection conn = DriverManager.getConnection(url,user,password);
                Statement st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                String sql = "SELECT rekammedis.idRekamMedis,rekammedis.noDataPasien,rekammedis.idDokter,rekammedis.diagnosa,rekammedis.tglKeluar,datapasien.tglMasuk,datapasien.ruanganKamar,datapasien.namaPasien,datapasien.jkPasien,datapasien.TglLahirPasien,datapasien.noHPPasien,datapasien.alamatPasien,datapasien.namaPenanggung,datapasien.noHPPenanggung,datapasien.jkPenanggung,datapasien.alamatPenanggung FROM rekammedis JOIN datapasien ON rekammedis.noDataPasien = datapasien.noDataPasien WHERE rekammedis.noDataPasien='"+table.getValueAt(table.getSelectedRow(),0)+"'";
                ResultSet rs = st.executeQuery(sql);
                if(rs.next()){
                    noDataPasien.setText(rs.getString("noDataPasien"));
                    SimpleDateFormat formatter1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ENGLISH);
                    Date tglmasuk = formatter1.parse(rs.getString("tglMasuk"));
                    tglMasuk.setDate(tglmasuk);
                    if(rs.getString("tglKeluar") != null){
                        SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
                        Date tglkeluar = formatter2.parse(rs.getString("tglKeluar"));
                        tglMasuk.setDate(tglkeluar);
                    }
                    diagnosaField.setText(rs.getString("diagnosa"));
                    ruanganKamar.setText(rs.getString("ruanganKamar"));
                    idDokter.setSelectedItem(rs.getString("idDokter"));
                    
                    namaPasien.setText(rs.getString("namaPasien"));
                    if(rs.getString("jkPasien").equals("Laki-laki")){
                        jkLakiPasien.setSelected(true);
                    }else{
                        jkPerempuanPasien.setSelected(true);
                    }
                    SimpleDateFormat formatter3 = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
                    Date tgllahir = formatter3.parse(rs.getString("TglLahirPasien"));
                    tglLahir.setDate(tgllahir);
                    alamatPasien.setText(rs.getString("alamatPasien"));
                    noHPPasien.setText(rs.getString("noHPPasien"));
                    
                    namaPenanggung.setText(rs.getString("namaPenanggung"));
                    if(rs.getString("jkPenanggung").equals("Laki-laki")){
                        jkLakiPenanggung.setSelected(true);
                    }else{
                        jkPerempuanPenanggung.setSelected(true);
                    }
                    alamatPenanggung.setText(rs.getString("alamatPasien"));
                    noHPPenanggung.setText(rs.getString("noHPPenanggung"));
                    
                }
//                aktif();
//                spesialis.setEnabled(false);
            }catch(SQLException e){
                System.out.println("Koneksi gagal"+e.toString());
            } catch (ParseException ex) {
                 Logger.getLogger(FormRekamMedis.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void namaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaDokterActionPerformed

    private void idDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDokterActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = DriverManager.getConnection(url,user,password);
            Statement st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT namaDokter FROM dokter WHERE idDokter LIKE '"+idDokter.getSelectedItem()+"%'";
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                namaDokter.setText(rs.getString("namaDokter"));
            }else{
                namaDokter.setText("");
            }
        }catch(SQLException e){
          System.out.println("Koneksi gagal"+e.toString());
        }
        
    }//GEN-LAST:event_idDokterActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        // TODO add your handling code here:
        tampilGrid(getDataSearch());
    }//GEN-LAST:event_cariBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRekamMedis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatPasien;
    private javax.swing.JTextArea alamatPenanggung;
    private javax.swing.JLabel blabka;
    private javax.swing.JLabel blabka1;
    private javax.swing.JLabel blabka2;
    private javax.swing.JLabel blabka3;
    private javax.swing.JLabel blabka5;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariField;
    private javax.swing.JTextArea diagnosaField;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JComboBox<String> idDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jkLakiPasien;
    private javax.swing.JRadioButton jkLakiPenanggung;
    private javax.swing.JRadioButton jkPerempuanPasien;
    private javax.swing.JRadioButton jkPerempuanPenanggung;
    private javax.swing.JTextField namaDokter;
    private javax.swing.JTextField namaPasien;
    private javax.swing.JTextField namaPenanggung;
    private javax.swing.JTextField noDataPasien;
    private javax.swing.JTextField noHPPasien;
    private javax.swing.JTextField noHPPenanggung;
    private javax.swing.ButtonGroup pasienGroup;
    private javax.swing.ButtonGroup penanggungGroup;
    private javax.swing.JTextField ruanganKamar;
    private javax.swing.JButton saveBtn;
    private com.toedter.calendar.JDateChooser tglKeluar;
    private com.toedter.calendar.JDateChooser tglLahir;
    private com.toedter.calendar.JDateChooser tglMasuk;
    // End of variables declaration//GEN-END:variables
}
